baseURL = "https://spolecneprooldrichov.cz/"
languageCode = "cs"
title = "Společně pro Oldřichov"
#theme = "simple"

[params]
  description = "Společně pro Oldřichov – nezávislí kandidáti do komunálních voleb 2026"

[menu]
  [[menu.main]]
    name = "Domů"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Co jsme udělali"
    url = "/co-jsme-udelali/"
    weight = 2

  [[menu.main]]
    name = "Co plánujeme"
    url = "/co-planujeme/"
    weight = 3

  [[menu.main]]
    name = "Kdo jsme"
    url = "/kandidati/"
    weight = 4

  [[menu.main]]
    name = "Kontakt"
    url = "/kontakt/"
    weight = 5
